# Generated by Django 2.1 on 2020-12-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201211_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
        migrations.RemoveField(
            model_name='userproduct',
            name='is_sold',
        ),
        migrations.DeleteModel(
            name='StockStatus',
        ),
    ]
