# Generated by Django 2.1 on 2020-12-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201211_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='userproduct',
            old_name='user_id',
            new_name='user',
        ),
    ]
