# Generated by Django 2.1 on 2020-12-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201211_1731'),
        ('product', '0005_auto_20201211_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.DeleteModel(
            name='UserProduct',
        ),
    ]
