# Generated by Django 2.1 on 2020-12-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201211_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
